# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'icsi.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication


class Ui_ICSIWindow(object):
    def setupUi(self, ICSIWindow):
        ICSIWindow.setObjectName("ICSIWindow")
        ICSIWindow.resize(960, 350)
        ICSIWindow.setMaximumSize(QtCore.QSize(960, 350))
        ICSIWindow.setStyleSheet("QMainWindow{\n"
        "background-image: url(:/nowyPrzedrostek/tlo.jpg);\n""}\n""")


        self.centralwidget = QtWidgets.QWidget(ICSIWindow)
        self.centralwidget.setObjectName("centralwidget")

        ## Button to train

        self.train = QtWidgets.QPushButton(self.centralwidget)
        self.train.setGeometry(QtCore.QRect(280, 100, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.train.setFont(font)
        self.train.setStyleSheet("background-color:white;\n"
                                  "color: black;\n"
                                  "")
        self.train.setObjectName("train")


        ## Button to detect

        self.detection = QtWidgets.QPushButton(self.centralwidget)
        self.detection.setGeometry(QtCore.QRect(500, 100, 211, 61))
        self.detection.setFont(font)
        self.detection.setStyleSheet("background-color:white;\n"
                                    "color: black;\n"
                                    "")
        self.detection.setObjectName("detection")

        ## Button to diplay film

        self.film = QtWidgets.QPushButton(self.centralwidget)
        self.film.setGeometry(QtCore.QRect(430, 170, 111, 51))
        font2 = QtGui.QFont()
        font2.setFamily("Byington")
        font2.setPointSize(12)
        font2.setBold(True)
        font2.setWeight(75)
        self.film.setFont(font2)
        self.film.setStyleSheet("background-color:white;\n"
                                       "color: black;")
        self.film.setCheckable(False)
        self.film.setObjectName("film")


        ## Button to exit

        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.clicked.connect(QApplication.instance().quit)
        self.exit.setGeometry(QtCore.QRect(800, 280, 151, 51))
        self.exit.setFont(font2)
        self.exit.setStyleSheet("background-color:white;\n"
                                "color: black;")
        self.exit.setObjectName("exit")


        ## ICSI Info

        self.ICSIInfo = QtWidgets.QPushButton(self.centralwidget)
        self.ICSIInfo.setGeometry(QtCore.QRect(10, 280, 171, 51))
        self.ICSIInfo.setFont(font2)
        self.ICSIInfo.setStyleSheet("background-color:white;\n"
                                    "color: black;\n"
                                    "")
        self.ICSIInfo.setObjectName("ICSIInfo")


        ## Mask Info

        self.MaskInfo = QtWidgets.QPushButton(self.centralwidget)
        self.MaskInfo.setGeometry(QtCore.QRect(330, 280, 311, 51))
        self.MaskInfo.setFont(font2)
        self.MaskInfo.setStyleSheet("background-color:white;\n"
                                    "color: black;")
        self.MaskInfo.setObjectName("MaskInfo")


        ## Title

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 0, 751, 81))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")


        ICSIWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ICSIWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName("menubar")
        ICSIWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ICSIWindow)
        self.statusbar.setObjectName("statusbar")
        ICSIWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ICSIWindow)
        QtCore.QMetaObject.connectSlotsByName(ICSIWindow)

    def retranslateUi(self, ICSIWindow):
        _translate = QtCore.QCoreApplication.translate
        ICSIWindow.setWindowTitle(_translate("ICSIWindow", "MainWindow"))
        self.train.setText(_translate("ICSIWindow", "Trenuj"))
        self.exit.setText(_translate("ICSIWindow", "Wyjście"))
        self.ICSIInfo.setText(_translate("ICSIWindow", "Procedura ICSI"))
        self.MaskInfo.setText(_translate("ICSIWindow", "Architektura sieci Mask R-CNN"))
        self.film.setText(_translate("ICSIWindow", "Zobacz film"))
        self.label_2.setText(_translate("ICSIWindow", "Oprogramowanie do rozpoznania czynności w procedurze in vitro \n"
        " z wykorzystaniem metod uczenia maszynowego"))
        self.detection.setText(_translate("ICSIWindow", "Uruchom detekcję"))

import images.tlo

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ICSIWindow = QtWidgets.QMainWindow()
    ui = Ui_ICSIWindow()
    ui.setupUi(ICSIWindow)
    ICSIWindow.show()
    sys.exit(app.exec_())
